/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sebaszayas (https://sketchfab.com/sebaszayas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chipa-dura-94662fd358c241e4aa7655bff267f66e
title: chipa Dura
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/donut.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.mat0_Box} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.mat0_Sphere} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.mat0_base} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.mat0_chipa} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.mat0_chipa} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.mat0_chipa} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.mat0_left_arm} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.mat0_left_eye} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.mat0_left_leg} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.mat0_right_arm} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.mat0_right_leg} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.mat0_rim_hat} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.mat0_rim_hat} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.mat1_left_arm} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.mat1_left_eye} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.mat1_left_leg} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.mat1_right_arm} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.mat1_right_leg} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.mat1_rim_hat} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.mat2_left_arm} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.mat2_left_eye} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.mat2_left_leg} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.mat2_right_arm} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.mat2_right_leg} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.mat2_rim_hat} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.mat3_left_eye} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.mat3_rim_hat} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.mat3_rim_hat} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.mat4_left_eye} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.mat5_left_eye} />
      </group>
    </group>
  )
}

useGLTF.preload('/donut.gltf')
