/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: CzernO (https://sketchfab.com/czernobog)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bananya-birbo-900ce1ec328e486296cfee70b9b13a45
title: Bananya Birbo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/heykel.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/heykel.gltf')
